name: lat_long_collector
description: Collect latitude and longitude
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  envied: ^0.3.0
  equatable: ^2.0.5
  file_picker: ^5.2.3
  flutter_bloc: ^8.1.1
  formz: ^0.4.1
  kiwi: ^4.0.3
  very_good_infinite_list: ^0.7.0
  yaml_writer: ^1.0.3

  draccoon_logger:
    path: packages/draccoon_logger
  kakao_address_handler:
    path: packages/kakao_address_handler

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  envied_generator: ^0.3.0
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
