name: draccoon_logger
description: logger for D.Raccoon
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  logger: ^1.1.0

dev_dependencies:
  flutter_lints: ^2.0.1